apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-duckdns-solver
rules:
  - apiGroups:
      - "acme.iti-gym-platform.duckdns.org"
    resources:
      - "*"
    verbs:
      - "create"
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-duckdns-solver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-duckdns-solver
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-duckdns-webhook-secret-reader
  namespace: cert-manager
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-duckdns-webhook-secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-duckdns-webhook-secret-reader
subjects:
  - kind: ServiceAccount
    name: cert-manager-duckdns-webhook
    namespace: cert-manager