apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: duckdns-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: duckdns-token
    creationPolicy: Owner
    template:
      data:
        token: "{{ .raw_token }}"
  data:
    - secretKey: raw_token
      remoteRef:
        key: ${SECRET_NAME_DUCKDNS}