apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: git-creds
    creationPolicy: Owner
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: gitops/image-updater/github-creds
        property: username
    - secretKey: password
      remoteRef:
        key: gitops/image-updater/github-creds
        property: password