apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: git-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          # Tells Argo CD and Image Updater to register this secret for Git auth
          argocd.argoproj.io/secret-type: repository
      data:
        type: "git"
        url: "https://github.com/HyperScale-Fitness-Platform/gym-platform-gitops.git"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: gitops/image-updater/github-creds
        property: username
    - secretKey: password
      remoteRef:
        key: gitops/image-updater/github-creds
        property: password