apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-admin-credentials
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: jenkins-admin-credentials
    creationPolicy: Owner
    template:
      data:
        jenkins-admin-user: "admin"
        jenkins-admin-password: "{{ .raw_password }}"
  data:
    - secretKey: raw_password
      remoteRef:
        key: ${SECRET_NAME}