apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-admin-credentials
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: jenkins-admin-credentials 
    creationPolicy: Owner              
  data:
    - secretKey: jenkins-admin-password
      remoteRef:
        key: "${SECRET_NAME}"